const translations = {
  tr: {
    navSolutions:'Çözümler',navProducts:'Briolight',navAker:'AKER Teknolojileri',navProcess:'Proje Modeli',navContact:'İletişim',navCta:'Demo Talebi',
    heroEyebrow:'Dijital Rehabilitasyon • Kapsayıcı Eğitim • Akıllı Eğitim Teknolojileri',heroTitle:'İnsan odaklı teknolojiyi <em>ölçülebilir etkiye</em> dönüştürüyoruz.',heroLead:'AKER Proje, kurumların eğitim ve rehabilitasyon ortamlarını; etkileşimli donanım, yazılım, danışmanlık, kurulum ve yerel destek ile uçtan uca dijitalleştirir.',heroPrimary:'Briolight Çözümlerini Keşfet',heroSecondary:'Proje Danışmanlığı Al',metricDevices:'cihazlık ekosistem',metricMethods:'egzersiz / yöntem',metricProjects:'Briolight proje deneyimi*',floatA1:'Platform',floatA2:'Briolight 5.0',floatB1:'Tek platform',floatB2:'Çoklu cihaz senaryoları',
    solutionsKicker:'Bütünleşik yaklaşım',solutionsTitle:'Tek ürün değil, kurumunuza göre tasarlanmış bir <em>çözüm mimarisi.</em>',solutionsLead:'Briolight; interaktif cihazları, rehabilitasyon yazılımını ve farklı terapi senaryolarını ortak bir platformda buluşturur. AKER; Türkiye\'de ihtiyaç analizi, proje tasarımı, entegrasyon, eğitim ve satış sonrası destek katmanını üstlenir.',
    sol1Title:'Kapsayıcı Eğitim',sol1Text:'Özel eğitim merkezleri, okullar ve destek eğitim ortamları için etkileşimli öğrenme ve bilişsel gelişim senaryoları.',sol2Title:'Dijital Rehabilitasyon',sol2Text:'Hastane ve rehabilitasyon merkezlerinde hareket, biliş, dikkat, koordinasyon ve terapi oturumlarını dijital içeriklerle destekleyen yapı.',sol3Title:'AgeTech & Yaşlı Bakımı',sol3Text:'Yaşlı kullanıcılar için kişiselleştirilebilir egzersiz planları, zorluk seviyeleri, skorlar ve görsel geri bildirimlerle desteklenen uygulamalar.',sol4Title:'Özel Terapi Alanları',sol4Text:'Tek odada tam sistem, ihtiyaca özel terapi odaları veya aynı cihazdan çoklu kurulum seçenekleriyle esnek ölçekleme.',learnMore:'Detayları gör →',
    platformTag:'Dijital İnteraktif Platform',platformKicker:'Briolight Platform',platformTitle:'Oyunlaştırılmış deneyim, kontrollü terapi akışı, ölçülebilir sonuçlar.',platformLead:'Platform; farklı kullanıcı etkileşim biçimlerini, özel efektleri, 3D içerikleri, ses ve görsel geri bildirimleri tek bir çalışma akışında birleştirebilir.',pf1Title:'Çoklu cihaz senaryoları',pf1Text:'Birden fazla cihazı aynı seans içinde birlikte çalıştırmaya uygun yapı.',pf2Title:'Egzersiz üretimi & kütüphane',pf2Text:'Egzersiz planlama, içerik kütüphanesi ve yeni metodolojiler için güncellenebilir yazılım yaklaşımı.',pf3Title:'İstatistik & veri toplama',pf3Text:'Seans sonuçlarını izleme, istatistik ve proje/araştırma amaçlı veri toplama yetenekleri.',
    productsKicker:'Briolight ürün ekosistemi',productsTitle:'Fiziksel alanı <em>etkileşimli bir terapi ve öğrenme ortamına</em> dönüştürün.',productsLead:'Sunumdaki 10 cihazlık ekosistem; tekil ürün olarak veya kuruma özel çoklu cihaz kombinasyonları halinde projelendirilebilir.',prodCategory:'BRIOLIGHT DEVICE',floorTitle:'Interactive Floor',floorText:'Hareketlere duyarlı büyük ölçekli zemin projeksiyonu; bilişsel süreçler, koordinasyon, dikkat ve hedefli hareket çalışmalarına yönelik içeriklerle kullanılabilir.',sandboxTitle:'Interactive Sandbox',sandboxText:'Gerçek kum, derinlik algılama ve projeksiyonu birleştirerek koordinasyon, hayal gücü ve duyusal-dokunsal etkileşimi destekleyen ortam.',panelTitle:'Interactive Panel',panelText:'Mobil stand üzerinde 32 veya 43 inç Android interaktif panel; temel bilişsel süreçler ve hareket koordinasyonu için Briolight yazılımıyla birlikte.',ecoKicker:'Ekosistemde ayrıca',ecoTitle:'7 tamamlayıcı cihaz / modül',
    versionKicker:'Platform evrimi',versionTitle:'4.0\'dan 5.0\'a: bağımsız cihazlardan <em>ağ merkezli dijital rehabilitasyona.</em>',versionLead:'Briolight sunumunda platformun güncel nesilleri; kapsayıcı eğitim, çoklu cihaz kombinasyonları, bulut servisleri ve 5.0 ile ağ-merkezli mimari doğrultusunda konumlandırılıyor.',v40Title:'Inclusive Education',v40a:'200 ön yüklü egzersiz',v40b:'4 bağımsız cihaz',v40c:'Bütünleşik yöntem yaklaşımı',mostFlexible:'ESNEK PLATFORM',v45Title:'Digital Interactive Rehabilitation',v45a:'Çocuk ve yetişkin rehabilitasyonu',v45b:'10 cihaza kadar kombinasyon',v45c:'Bulut üzerinden içerik güncelleme',v50Title:'Network-Centric Platform',v50a:'Web portalı + mobil uygulama entegrasyonu',v50b:'Çok dilli yapı ve paylaşılabilir playlist\'ler',v50c:'AI/ML teknolojilerine yönelik mimari',
    processKicker:'AKER proje modeli',processTitle:'Tekliften önce <em>doğru sistemi</em> tasarlarız.',processLead:'Kurumunuzun hedef kitlesi, fiziksel alanı, operasyonel süreci ve bütçesine göre optimum konfigürasyonu belirleyip kurulum, eğitim ve destek planıyla birlikte sunuyoruz.',step1Title:'Keşif & İhtiyaç Analizi',step1Text:'Kullanıcı grupları, terapi/eğitim hedefleri, mekan ve mevcut altyapı.',step2Title:'Çözüm Tasarımı',step2Text:'Cihaz kombinasyonu, yazılım, lisans ve mekan yerleşimi.',step3Title:'Kurulum & Entegrasyon',step3Text:'Donanım kurulumu, ağ/ekran altyapısı ve devreye alma.',step4Title:'Eğitim & Kullanıma Alma',step4Text:'Kurum ekibi için uygulamalı kullanım eğitimi ve senaryo hazırlığı.',step5Title:'Servis & Gelişim',step5Text:'Bakım, güncelleme, içerik ve yeni ihtiyaçlar için sürdürülebilir destek.',
    akerKicker:'AKER teknoloji portföyü',akerTitle:'Eğitim ortamları için <em>akıllı sunum ve ses çözümleri.</em>',akerLead:'AKER\'ın mevcut elektronik ve dijital kürsü ürünleri; sınıf, konferans salonu, üniversite ve kurumsal sunum alanlarında güçlü ses, dokunmatik içerik yönetimi ve entegre sunum deneyimi sunar.',lecternTitle:'Ses Sistemli Elektronik Kürsü',lecternText:'100 W RMS dahili ses sistemi, gooseneck ve kablosuz mikrofon desteği; sınıf ve salonlarda tek gövdede profesyonel ses çözümü.',digitalLecternTitle:'Dijital Akıllı Kürsü',digitalLecternText:'27 inç dokunmatik ekran, dahili bilgisayar, mikrofon yönetimi, anotasyon ve elektrikli yükseklik ayarıyla bütünleşik sunum istasyonu.',getQuote:'Teklif alın →',
    proofKicker:'Araştırma & uygulama',proofTitle:'Teknoloji, yöntem ve saha uygulamasını aynı çatı altında ele alan yaklaşım.',proofText:'Briolight sunumunda bilimsel araştırma, yazılım geliştirme, mühendislik, üretim, kurulum ve eğitim tek bir değer zincirinin parçaları olarak konumlandırılıyor. Platformun farklı rehabilitasyon merkezleri, eğitim kurumları ve araştırma ortamlarında kullanıldığı belirtiliyor.',proofCta:'Türkiye uygulama modeli için görüşelim',
    contactKicker:'Yeni proje',contactTitle:'Kurumunuz için doğru Briolight konfigürasyonunu birlikte tasarlayalım.',contactLead:'Demo, keşif, teknik toplantı, ürün seçimi veya bütçe çalışması için AKER Proje ekibiyle iletişime geçin.',address:'Fidanlık Mah. Sağlık 1 Sk. Güzelsu İşhanı No:59/34, Çankaya / Ankara',formName:'Ad Soyad',formOrg:'Kurum',formEmail:'E-posta',formInterest:'İlgilendiğiniz çözüm',formMessage:'Kısaca ihtiyacınız',formSubmit:'Görüşme Talebi Gönder',formNote:'Form, e-posta istemcinizde önceden doldurulmuş bir mesaj açar.',
    footerText:'Eğitim teknolojileri, dijital rehabilitasyon ve kurumsal proje entegrasyonu.',footerSolutions:'Çözümler',footerLecterns:'Akıllı Kürsüler',footerConsulting:'Proje Danışmanlığı',footerContact:'İletişim',rights:'Tüm hakları saklıdır.',medicalNote:'* Üretici sunumundaki proje sayısıdır. Tıbbi kullanım ve ürün sınıflandırması ilgili mevzuat ve konfigürasyona göre değerlendirilmelidir.'
  },
  en: {
    navSolutions:'Solutions',navProducts:'Briolight',navAker:'AKER Technologies',navProcess:'Project Model',navContact:'Contact',navCta:'Request Demo',
    heroEyebrow:'Digital Rehabilitation • Inclusive Education • Smart Education Technologies',heroTitle:'We turn human-centered technology into <em>measurable impact.</em>',heroLead:'AKER Proje helps institutions digitize learning and rehabilitation environments end-to-end with interactive hardware, software, consulting, installation and local support.',heroPrimary:'Explore Briolight Solutions',heroSecondary:'Get Project Consulting',metricDevices:'device ecosystem',metricMethods:'workouts / methods',metricProjects:'Briolight project experience*',floatA1:'Platform',floatA2:'Briolight 5.0',floatB1:'One platform',floatB2:'Multi-device scenarios',
    solutionsKicker:'Integrated approach',solutionsTitle:'Not a single product — a <em>solution architecture</em> designed for your institution.',solutionsLead:'Briolight brings interactive devices, rehabilitation software and multiple therapeutic scenarios into a common platform. AKER adds needs analysis, solution design, integration, training and after-sales support in Türkiye.',
    sol1Title:'Inclusive Education',sol1Text:'Interactive learning and cognitive-development scenarios for special education centers, schools and support-learning environments.',sol2Title:'Digital Rehabilitation',sol2Text:'A digital structure designed to support movement, cognition, attention, coordination and rehabilitation sessions in hospitals and rehabilitation centers.',sol3Title:'AgeTech & Elderly Care',sol3Text:'Customizable workouts, difficulty levels, scoring and visual feedback designed for elderly users.',sol4Title:'Specialized Therapy Spaces',sol4Text:'Flexible configurations: full system in one room, dedicated therapy rooms, or multiple installations of the same device.',learnMore:'See details →',
    platformTag:'Digital Interactive Platform',platformKicker:'Briolight Platform',platformTitle:'Gamified experience, controlled workflows, measurable session data.',platformLead:'The platform can combine different interaction modes, special effects, 3D content, sound and visual feedback into a single workflow.',pf1Title:'Multi-device scenarios',pf1Text:'Designed for combinations where several devices participate in one session.',pf2Title:'Workout generation & library',pf2Text:'Workout planning, content libraries and an updateable software approach for new methodologies.',pf3Title:'Statistics & data collection',pf3Text:'Session result tracking, statistics and data collection capabilities for project and research use.',
    productsKicker:'Briolight product ecosystem',productsTitle:'Turn physical space into an <em>interactive rehabilitation and learning environment.</em>',productsLead:'The 10-device ecosystem in the presentation can be configured as individual products or as institution-specific multi-device solutions.',prodCategory:'BRIOLIGHT DEVICE',floorTitle:'Interactive Floor',floorText:'Large movement-sensitive floor projection designed for cognitive processes, coordination, attention and targeted-movement activities.',sandboxTitle:'Interactive Sandbox',sandboxText:'Combines real sand, depth sensing and projection to support coordination, imagination and sensory-tactile interaction.',panelTitle:'Interactive Panel',panelText:'32 or 43-inch Android interactive panel on a mobile stand, supplied with Briolight software for basic cognitive processes and movement coordination.',ecoKicker:'The ecosystem also includes',ecoTitle:'7 complementary devices / modules',
    versionKicker:'Platform evolution',versionTitle:'From 4.0 to 5.0: from standalone devices to <em>network-centric digital rehabilitation.</em>',versionLead:'The Briolight presentation positions its current generations around inclusive education, multi-device combinations, cloud services and, in 5.0, a network-centric architecture.',v40Title:'Inclusive Education',v40a:'200 pre-installed exercises',v40b:'4 standalone devices',v40c:'Integrated methodology approach',mostFlexible:'FLEXIBLE PLATFORM',v45Title:'Digital Interactive Rehabilitation',v45a:'Children and adult rehabilitation',v45b:'Combinations of up to 10 devices',v45c:'Cloud-based content updates',v50Title:'Network-Centric Platform',v50a:'Web portal + mobile app integration',v50b:'Multilingual support and shareable playlists',v50c:'Architecture incorporating AI/ML technologies',
    processKicker:'AKER project model',processTitle:'We design the <em>right system</em> before we quote it.',processLead:'We determine the optimum configuration based on your target users, physical space, operating model and budget, then deliver it with installation, training and support plans.',step1Title:'Discovery & Needs Analysis',step1Text:'User groups, therapy/education objectives, space and existing infrastructure.',step2Title:'Solution Design',step2Text:'Device combination, software, licensing and room layout.',step3Title:'Installation & Integration',step3Text:'Hardware installation, network/display infrastructure and commissioning.',step4Title:'Training & Go-Live',step4Text:'Hands-on staff training and scenario preparation.',step5Title:'Service & Evolution',step5Text:'Maintenance, updates, content and sustainable support for new needs.',
    akerKicker:'AKER technology portfolio',akerTitle:'Smart presentation and audio solutions for <em>modern learning environments.</em>',akerLead:'AKER’s electronic and digital lectern products provide integrated audio, touch content control and presentation workflows for classrooms, conference halls, universities and corporate venues.',lecternTitle:'Integrated Audio Lectern',lecternText:'100 W RMS integrated sound, gooseneck and wireless microphone support — a professional one-body audio solution for classrooms and halls.',digitalLecternTitle:'Digital Smart Lectern',digitalLecternText:'27-inch touch display, embedded computer, microphone control, annotation and electric height adjustment in one presentation station.',getQuote:'Request quote →',
    proofKicker:'Research & implementation',proofTitle:'An approach that brings technology, methodology and field implementation together.',proofText:'The Briolight presentation positions scientific research, software development, engineering, manufacturing, installation and training as parts of one value chain, and states that the platform is used across rehabilitation, education and research environments.',proofCta:'Discuss a Türkiye implementation model',
    contactKicker:'New project',contactTitle:'Let’s design the right Briolight configuration for your institution.',contactLead:'Contact AKER Proje for a demo, site discovery, technical meeting, product selection or budget study.',address:'Fidanlık Mah. Sağlık 1 St. Güzelsu Business Center No:59/34, Çankaya / Ankara, Türkiye',formName:'Full name',formOrg:'Organization',formEmail:'Email',formInterest:'Solution of interest',formMessage:'Briefly describe your need',formSubmit:'Request a Meeting',formNote:'The form opens a pre-filled message in your email client.',
    footerText:'Education technology, digital rehabilitation and institutional project integration.',footerSolutions:'Solutions',footerLecterns:'Smart Lecterns',footerConsulting:'Project Consulting',footerContact:'Contact',rights:'All rights reserved.',medicalNote:'* Project count stated in the manufacturer presentation. Medical use and product classification should be evaluated according to the applicable regulations and configuration.'
  }
};

const ecosystem = {
  tr:['Interactive Wall','Gross Motor Skills Controller','Fine Motor Skills Controller','Logopedic / Voice Therapy Mirror','Interactive Metronome','Interactive Gyroscopes','Self-Control Training Module'],
  en:['Interactive Wall','Gross Motor Skills Controller','Fine Motor Skills Controller','Logopedic / Voice Therapy Mirror','Interactive Metronome','Interactive Gyroscopes','Self-Control Training Module']
};
const products = {
  floor:{image:'/public/assets/interactive-floor.webp',title:{tr:'Interactive Floor',en:'Interactive Floor'},text:{tr:'150 × 100 cm\'den başlayan büyük ölçekli, insan hareketlerine duyarlı zemin projeksiyonu. Briolight sunumunda konsantrasyon, hafıza, tanıma, dikkat, hedefli hareket ve bilişsel çalışmalar için örneklenir.',en:'Large movement-sensitive floor projection starting from 150 × 100 cm. The Briolight presentation illustrates use cases around concentration, memory, recognition, attention, targeted movement and cognitive work.'}},
  sandbox:{image:'/public/assets/interactive-sandbox.webp',title:{tr:'Interactive Sandbox',en:'Interactive Sandbox'},text:{tr:'Gerçek kum yüzeyine derinlik sistemi ve yazılımla projeksiyon bindiren interaktif çözüm. Sunumda koordinasyon, hayal gücü ve duyusal-dokunsal terapi öğelerini destekleyen bir ortam olarak konumlandırılır.',en:'An interactive solution that combines real sand with depth sensing, software and projection. The presentation positions it as supporting coordination, imagination and sensory-tactile therapy elements.'}},
  panel:{image:'/public/assets/interactive-panel.webp',title:{tr:'Interactive Panel',en:'Interactive Panel'},text:{tr:'32 veya 43 inç seçenekli, tekerlekli mobil stand üzerinde Android tabanlı interaktif panel. Briolight rehabilitasyon yazılımı ön yüklü olarak; temel bilişsel süreçler ve hareket koordinasyonuna yönelik egzersizleri destekler.',en:'Android-based interactive panel in 32 or 43-inch options on a mobile wheeled stand. Supplied with Briolight rehabilitation software for exercises focused on basic cognitive processes and movement coordination.'}}
};

let lang = localStorage.getItem('aker-lang') || 'tr';
const htmlKeys = new Set(['heroTitle','solutionsTitle','versionTitle','processTitle','akerTitle','productsTitle']);
function applyLanguage(next){
  lang=next; localStorage.setItem('aker-lang',lang); document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n; const val=translations[lang][key]; if(!val) return; if(htmlKeys.has(key)) el.innerHTML=val; else el.textContent=val;});
  document.getElementById('langSwitch').textContent=lang==='tr'?'EN':'TR';
  document.title = lang==='tr' ? 'AKER Proje | Dijital Rehabilitasyon & Eğitim Teknolojileri' : 'AKER Proje | Digital Rehabilitation & Education Technologies';
  renderEcosystem();
}
function renderEcosystem(){document.getElementById('ecoList').innerHTML=ecosystem[lang].map(x=>`<span class="eco-chip">${x}</span>`).join('')}

document.getElementById('langSwitch').addEventListener('click',()=>applyLanguage(lang==='tr'?'en':'tr'));
const menu=document.getElementById('nav'), toggle=document.getElementById('menuToggle');
toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));

const observer = new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();

const modal=document.getElementById('productModal'), modalContent=document.getElementById('modalContent');
function openProduct(id){const p=products[id]; if(!p)return; modalContent.innerHTML=`<img class="modal-image" src="${p.image}" alt="${p.title[lang]}"><div class="modal-body"><small>BRIOLIGHT DEVICE</small><h3>${p.title[lang]}</h3><p>${p.text[lang]}</p><a class="btn btn-gold" href="#contact" onclick="document.getElementById('productModal').close()">${lang==='tr'?'Bu ürün için görüşelim':'Discuss this product'}</a></div>`;modal.showModal()}
document.querySelectorAll('[data-product]').forEach(card=>{card.addEventListener('click',()=>openProduct(card.dataset.product));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProduct(card.dataset.product)}})});
document.getElementById('modalClose').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=lang==='tr'?'AKER Proje - Görüşme / Demo Talebi':'AKER Proje - Meeting / Demo Request';const body=lang==='tr'?`Merhaba AKER Proje,%0D%0A%0D%0AAd Soyad: ${encodeURIComponent(f.get('name'))}%0D%0AKurum: ${encodeURIComponent(f.get('organization'))}%0D%0AE-posta: ${encodeURIComponent(f.get('email'))}%0D%0Aİlgilendiğim çözüm: ${encodeURIComponent(f.get('interest'))}%0D%0A%0D%0Aİhtiyacım:%0D%0A${encodeURIComponent(f.get('message'))}`:`Hello AKER Proje,%0D%0A%0D%0AName: ${encodeURIComponent(f.get('name'))}%0D%0AOrganization: ${encodeURIComponent(f.get('organization'))}%0D%0AEmail: ${encodeURIComponent(f.get('email'))}%0D%0AInterest: ${encodeURIComponent(f.get('interest'))}%0D%0A%0D%0AMessage:%0D%0A${encodeURIComponent(f.get('message'))}`;window.location.href=`mailto:akerprojeegitim@gmail.com?subject=${encodeURIComponent(subject)}&body=${body}`});
applyLanguage(lang);
